"project_id": "1605"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_url": "https://serhiy.api.crowdin.com"
"base_path": "."

"preserve_hierarchy": true

files:
  - source: /**/*.mdx
    translation: /%two_letters_code%/**/%original_file_name%
    ignore:
      - /uk/**
      - /es/**
      - /et/**
      - /fr/**
      - /de/**
      - /ja/**
      - /jp/**
      - /ko/**
      - /pt/**
      - /pt-BR/**
      - /ru/**
      - /zh/**
      - /zh-Hans/**
      - /zh-Hant/**
      - /ar/**
      - /it/**
      - /tr/**
      - /id/**
      - /node_modules/**
